<a href="https://colab.research.google.com/github/ShrutiMishra-2002/Ps4/blob/main/expt7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np

Arithmetic Operations

addition:-

In [14]:
# Defining both the matrices
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

# Performing addition using arithmetic operator
add_ans = a+b
print(add_ans)

# Performing addition using numpy function
add_ans = np.add(a, b)
print(add_ans)

[  7  77  23 130]
[  7  77  23 130]


subtraction:-

In [13]:
import numpy as np

# Defining both the matrices
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

# Performing subtraction using arithmetic operator
sub_ans = a-b
print(sub_ans)

# Performing subtraction using numpy function
sub_ans = np.subtract(a, b)
print(sub_ans)


[ 3 67  3 70]
[ 3 67  3 70]


Multiplication

In [ ]:
# Defining both the matrices
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

# Performing multiplication using arithmetic operator
mul_ans = a*b
print(mul_ans)

# Performing multiplication using numpy function
mul_ans = np.multiply(a, b)
print(mul_ans)


Broadcasting

In [10]:
import pandas as pd
from timeit import Timer

Single Dimension array 

In [8]:
a = np.array([17, 11, 19]) # 1x3 Dimension array
print(a)
b = 3
print(b)

# Broadcasting happened because of
# miss match in array Dimension.
c = a + b
print(c)


[17 11 19]
3
[20 14 22]


Two Dimensional Array 

In [9]:
A = np.array([[11, 22, 33], [10, 20, 30]])
print(A)

b = 4
print(b)

C = A + b
print(C)


[[11 22 33]
 [10 20 30]]
4
[[15 26 37]
 [14 24 34]]


Vectorization 

In [12]:
 
# Creating a large array of size 10**5
array = np.random.randint(1000, size=10**5)
 
def sum_using_forloop():
  sum_array=0
  for element in array:
    sum_array += element
 
def sum_using_builtin_method():
  sum_array = sum(array)
 
def sum_using_numpy():
  sum_array = np.sum(array)
 
time_forloop = Timer(sum_using_forloop).timeit(1)
time_builtin = Timer(sum_using_builtin_method).timeit(1)
time_numpy = Timer(sum_using_numpy).timeit(1)
 
print("Summing elements takes %0.9f units using for loop"%time_forloop)
print("Summing elements takes %0.9f units using builtin method"%time_builtin)
print("Summing elements takes %0.9f units using numpy"%time_numpy)
 
print()
 
def max_using_forloop():
  maximum=array[0]
  for element in array:
    if element > maximum:
      maximum = element
 
def max_using_builtin_method():
  maximum = max(array)
 
def max_using_numpy():
  maximum = np.max(array)
 
time_forloop = Timer(max_using_forloop).timeit(1)
time_builtin = Timer(max_using_builtin_method).timeit(1)
time_numpy = Timer(max_using_numpy).timeit(1)
 
print("Finding maximum element takes %0.9f units using for loop"%time_forloop)
print("Finding maximum element takes %0.9f units using built-in method"%time_builtin)
print("Finding maximum element takes %0.9f units using numpy"%time_numpy)



Summing elements takes 0.009959332 units using for loop
Summing elements takes 0.006977483 units using builtin method
Summing elements takes 0.000118579 units using numpy

Finding maximum element takes 0.006658149 units using for loop
Finding maximum element takes 0.005181230 units using built-in method
Finding maximum element takes 0.000184713 units using numpy
